import { NextResponse } from "next/server";
import { getDbAsync, isLocalGatewayMode } from "@market-standard/db";
import { releaseNotes, releaseRepos } from "@market-standard/db/schema/release";
import { and, eq } from "@market-standard/db/query";
import { getOwnerId } from "@/lib/owner";

interface GitHubPull {
  number: number;
  title: string;
  merged_at: string | null;
  user: { login: string };
}

interface GitHubTag {
  name: string;
}

function githubHeaders(): HeadersInit {
  const token = process.env.GITHUB_TOKEN;
  return {
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  };
}

async function githubFetch<T>(url: string): Promise<T> {
  const res = await fetch(url, { headers: githubHeaders(), next: { revalidate: 0 } });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub API error ${res.status}: ${text.slice(0, 200)}`);
  }
  return res.json() as Promise<T>;
}

async function generateMarkdown(repoFullName: string): Promise<{ version: string; title: string; bodyMd: string }> {
  const [owner, repo] = repoFullName.split("/");
  const tags = await githubFetch<GitHubTag[]>(
    `https://api.github.com/repos/${owner}/${repo}/tags?per_page=1`,
  );
  const lastTag = tags[0]?.name ?? null;

  let sinceIso: string | null = null;
  if (lastTag) {
    try {
      const ref = await githubFetch<{ object: { sha: string } }>(
        `https://api.github.com/repos/${owner}/${repo}/git/ref/tags/${encodeURIComponent(lastTag)}`,
      );
      const commit = await githubFetch<{ committer: { date: string } }>(
        `https://api.github.com/repos/${owner}/${repo}/git/commits/${ref.object.sha}`,
      );
      sinceIso = commit.committer.date;
    } catch {
      // Tag may be lightweight; continue without date filter
    }
  }

  const pulls = await githubFetch<GitHubPull[]>(
    `https://api.github.com/repos/${owner}/${repo}/pulls?state=closed&per_page=100&sort=updated&direction=desc`,
  );

  const merged = pulls.filter((pr) => {
    if (!pr.merged_at) return false;
    if (!sinceIso) return true;
    return new Date(pr.merged_at) > new Date(sinceIso);
  });

  const version = lastTag ? bumpPatch(lastTag) : "v0.1.0";
  const title = `Release ${version}`;

  const lines = [
    `# ${title}`,
    "",
    lastTag ? `Changes since \`${lastTag}\`:` : "Initial release:",
    "",
  ];

  if (merged.length === 0) {
    lines.push("_No merged pull requests found._");
  } else {
    for (const pr of merged) {
      lines.push(`- ${pr.title} ([#${pr.number}](https://github.com/${owner}/${repo}/pull/${pr.number})) — @${pr.user.login}`);
    }
  }

  lines.push("", "---", "_Generated by Standard Release_");

  return { version, title, bodyMd: lines.join("\n") };
}

function bumpPatch(tag: string): string {
  const cleaned = tag.replace(/^v/, "");
  const parts = cleaned.split(".");
  if (parts.length >= 3) {
    const patch = Number(parts[2]);
    if (!Number.isNaN(patch)) {
      parts[2] = String(patch + 1);
      return (tag.startsWith("v") ? "v" : "") + parts.join(".");
    }
  }
  return tag.startsWith("v") ? `${tag}.1` : `v${cleaned}.1`;
}

interface GenerateRouteProps {
  params: Promise<{ id: string }>;
}

export async function POST(_request: Request, { params }: GenerateRouteProps) {
  const ownerId = await getOwnerId();
  if (!ownerId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id } = await params;

  let repo: typeof releaseRepos.$inferSelect | null = null;

  if (isLocalGatewayMode()) {
    const { fetchGateway, postGateway } = await import("@market-standard/db");
    repo = await fetchGateway<typeof releaseRepos.$inferSelect>(`/release/repos/${id}`).catch(() => null);
    if (!repo) {
      return NextResponse.json({ error: "Repo not found" }, { status: 404 });
    }

    const generated = await generateMarkdown(repo.repoFullName).catch((err: Error) => {
      return { error: err.message } as const;
    });
    if ("error" in generated) {
      return NextResponse.json({ error: generated.error }, { status: 502 });
    }

    const note = await postGateway<typeof releaseNotes.$inferSelect>("/release/notes", {
      repoId: repo.id,
      version: generated.version,
      title: generated.title,
      bodyMd: generated.bodyMd,
    });
    return NextResponse.json(note, { status: 201 });
  }

  const db = await getDbAsync();
  const [row] = await db
    .select()
    .from(releaseRepos)
    .where(and(eq(releaseRepos.id, id), eq(releaseRepos.ownerId, ownerId)))
    .limit(1);
  if (!row) {
    return NextResponse.json({ error: "Repo not found" }, { status: 404 });
  }
  repo = row;

  try {
    const generated = await generateMarkdown(repo.repoFullName);
    const [note] = await db
      .insert(releaseNotes)
      .values({
        repoId: repo.id,
        version: generated.version,
        title: generated.title,
        bodyMd: generated.bodyMd,
      })
      .returning();

    return NextResponse.json(note, { status: 201 });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Generation failed";
    return NextResponse.json({ error: message }, { status: 502 });
  }
}
