import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

interface AppSpec {
  dir: string;
  port: number;
  /** Sibling URLs to expose via NEXT_PUBLIC_*_URL */
  siblings?: Partial<Record<"polls" | "proof" | "metrics" | "hook" | "release" | "vault" | "links" | "snippets" | "status" | "regex" | "postmortem" | "floodg8" | "syncdevtime", string>>;
}

const APPS: AppSpec[] = [
  { dir: "apps/standard-polls", port: 3001, siblings: { proof: "http://localhost:3002", metrics: "http://localhost:3003" } },
  { dir: "apps/standard-proof", port: 3002, siblings: { polls: "http://localhost:3001", metrics: "http://localhost:3003" } },
  { dir: "apps/standard-metrics", port: 3003, siblings: { polls: "http://localhost:3001", proof: "http://localhost:3002" } },
  { dir: "apps/standard-hook", port: 3004, siblings: { polls: "http://localhost:3001", proof: "http://localhost:3002", metrics: "http://localhost:3003", release: "http://localhost:3005" } },
  { dir: "apps/standard-release", port: 3005, siblings: { polls: "http://localhost:3001", proof: "http://localhost:3002", metrics: "http://localhost:3003", hook: "http://localhost:3004" } },
  { dir: "apps/standard-links", port: 3007, siblings: { metrics: "http://localhost:3003" } },
  { dir: "apps/standard-vault", port: 3006, siblings: { metrics: "http://localhost:3003" } },
  { dir: "apps/standard-snippets", port: 3008, siblings: { metrics: "http://localhost:3003", hook: "http://localhost:3004", release: "http://localhost:3005" } },
  { dir: "apps/standard-status", port: 3009, siblings: { hook: "http://localhost:3004", release: "http://localhost:3005", snippets: "http://localhost:3008" } },
  { dir: "apps/standard-regex", port: 3010, siblings: { snippets: "http://localhost:3008", hook: "http://localhost:3004", vault: "http://localhost:3006" } },
  { dir: "apps/standard-postmortem", port: 3011, siblings: { hook: "http://localhost:3004", status: "http://localhost:3009", snippets: "http://localhost:3008" } },
];

const HEADER = `# Auto-generated by scripts/sync-local-env.ts — do not commit secrets here
# Re-run \`pnpm db:setup\` to refresh.
NEXT_PUBLIC_LOCAL_DEV=true
LOCAL_DEV=true
DATABASE_URL=postgresql://127.0.0.1:54322/postgres
DB_GATEWAY_URL=http://127.0.0.1:4000
`;

function envForApp(app: AppSpec): string {
  const lines = [HEADER, `NEXT_PUBLIC_APP_URL=http://localhost:${app.port}`];
  if (app.siblings) {
    for (const [key, url] of Object.entries(app.siblings)) {
      const upper = key.charAt(0).toUpperCase() + key.slice(1);
      lines.push(`NEXT_PUBLIC_${upper.toUpperCase()}_URL=${url}`);
    }
  }
  return `${lines.join("\n")}\n`;
}

let written = 0;
for (const app of APPS) {
  const envPath = path.join(ROOT, app.dir, ".env.local");
  fs.writeFileSync(envPath, envForApp(app), "utf8");
  console.log(`Wrote ${path.relative(ROOT, envPath)}`);
  written += 1;
}
console.log(`\n${written} env files synced. Local dev ready: pnpm dev:local`);
