// AUTO-GENERATED by scripts/gen-sdk.ts — do not edit by hand.
import { ApiClient, type ApiClientOptions } from "../base";

/**
 * Typed client for standard-cron. Construct with a baseUrl pointing at the
 * app origin (e.g. https://standard-lens.vercel.app). All methods return the
 * parsed JSON response and throw ApiError on non-2xx responses.
 */
export class CronClient extends ApiClient {
  constructor(opts: ApiClientOptions = {}) {
    super(opts);
  }
  /** GET /api/docs */
  listDocs(): Promise<any> {
    return this.get<any>(`/api/docs`);
  }
  /** GET /api/health */
  listHealth(): Promise<any> {
    return this.get<any>(`/api/health`);
  }
  /** POST /api/heartbeat/{token} */
  postHeartbeatToken(token: string, body?: any): Promise<any> {
    return this.post<any>(`/api/heartbeat/${token}`, body);
  }
  /** GET /api/jobs */
  listJobs(): Promise<any> {
    return this.get<any>(`/api/jobs`);
  }
  /** POST /api/jobs */
  createJob(body?: any): Promise<any> {
    return this.post<any>(`/api/jobs`, body);
  }
  /** GET /api/jobs/{id} */
  getJob(id: string): Promise<any> {
    return this.get<any>(`/api/jobs/${id}`);
  }
  /** PATCH /api/jobs/{id} */
  updateJob(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/jobs/${id}`, body);
  }
  /** DELETE /api/jobs/{id} */
  deleteJob(id: string): Promise<any> {
    return this.delete<any>(`/api/jobs/${id}`);
  }
  /** POST /api/jobs/{id}/runs */
  createRun(id: string, body?: any): Promise<any> {
    return this.post<any>(`/api/jobs/${id}/runs`, body);
  }
  /** GET /api/notifications */
  listNotifications(): Promise<any> {
    return this.get<any>(`/api/notifications`);
  }
  /** POST /api/notifications */
  createNotification(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications`, body);
  }
  /** PATCH /api/notifications/{id}/read */
  updateRead(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/notifications/${id}/read`, body);
  }
  /** POST /api/notifications/read-all */
  createReadAll(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications/read-all`, body);
  }
  /** GET /api/openapi.json */
  listOpenapiJson(): Promise<any> {
    return this.get<any>(`/api/openapi.json`);
  }
  /** GET /api/team */
  listTeam(): Promise<any> {
    return this.get<any>(`/api/team`);
  }
  /** POST /api/team */
  createTeam(body?: any): Promise<any> {
    return this.post<any>(`/api/team`, body);
  }
  /** GET /api/team/{teamId}/invitations */
  listInvitations(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/invitations`);
  }
  /** POST /api/team/{teamId}/invitations */
  createInvitation(teamId: string, body?: any): Promise<any> {
    return this.post<any>(`/api/team/${teamId}/invitations`, body);
  }
  /** GET /api/team/{teamId}/members */
  listMembers(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/members`);
  }
  /** PATCH /api/team/{teamId}/members/{memberId} */
  updateMember(teamId: string, memberId: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/team/${teamId}/members/${memberId}`, body);
  }
  /** DELETE /api/team/{teamId}/members/{memberId} */
  deleteMember(teamId: string, memberId: string): Promise<any> {
    return this.delete<any>(`/api/team/${teamId}/members/${memberId}`);
  }
  /** POST /api/webhooks/stripe */
  createStripe(body?: any): Promise<any> {
    return this.post<any>(`/api/webhooks/stripe`, body);
  }
}

export const createCronClient = (opts?: ApiClientOptions) => new CronClient(opts);
