// AUTO-GENERATED by scripts/gen-sdk.ts — do not edit by hand.
import { ApiClient, type ApiClientOptions } from "../base";

/**
 * Typed client for standard-metrics. Construct with a baseUrl pointing at the
 * app origin (e.g. https://standard-lens.vercel.app). All methods return the
 * parsed JSON response and throw ApiError on non-2xx responses.
 */
export class MetricsClient extends ApiClient {
  constructor(opts: ApiClientOptions = {}) {
    super(opts);
  }
  /** GET /api/cron/sync */
  listSync(): Promise<any> {
    return this.get<any>(`/api/cron/sync`);
  }
  /** GET /api/docs */
  listDocs(): Promise<any> {
    return this.get<any>(`/api/docs`);
  }
  /** GET /api/health */
  listHealth(): Promise<any> {
    return this.get<any>(`/api/health`);
  }
  /** GET /api/metrics/export */
  listExport(): Promise<any> {
    return this.get<any>(`/api/metrics/export`);
  }
  /** GET /api/notifications */
  listNotifications(): Promise<any> {
    return this.get<any>(`/api/notifications`);
  }
  /** POST /api/notifications */
  createNotification(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications`, body);
  }
  /** PATCH /api/notifications/{id}/read */
  updateRead(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/notifications/${id}/read`, body);
  }
  /** POST /api/notifications/read-all */
  createReadAll(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications/read-all`, body);
  }
  /** GET /api/openapi.json */
  listOpenapiJson(): Promise<any> {
    return this.get<any>(`/api/openapi.json`);
  }
  /** GET /api/payment-links */
  listPaymentLinks(): Promise<any> {
    return this.get<any>(`/api/payment-links`);
  }
  /** POST /api/payment-links */
  createPaymentLink(body?: any): Promise<any> {
    return this.post<any>(`/api/payment-links`, body);
  }
  /** PATCH /api/payment-links/{id} */
  updatePaymentLink(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/payment-links/${id}`, body);
  }
  /** DELETE /api/payment-links/{id} */
  deletePaymentLink(id: string): Promise<any> {
    return this.delete<any>(`/api/payment-links/${id}`);
  }
  /** GET /api/quota */
  listQuota(): Promise<any> {
    return this.get<any>(`/api/quota`);
  }
  /** POST /api/quota */
  createQuota(body?: any): Promise<any> {
    return this.post<any>(`/api/quota`, body);
  }
  /** GET /api/stripe/callback */
  listCallback(): Promise<any> {
    return this.get<any>(`/api/stripe/callback`);
  }
  /** GET /api/stripe/connect */
  listConnect(): Promise<any> {
    return this.get<any>(`/api/stripe/connect`);
  }
  /** GET /api/team */
  listTeam(): Promise<any> {
    return this.get<any>(`/api/team`);
  }
  /** POST /api/team */
  createTeam(body?: any): Promise<any> {
    return this.post<any>(`/api/team`, body);
  }
  /** GET /api/team/{teamId}/invitations */
  listInvitations(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/invitations`);
  }
  /** POST /api/team/{teamId}/invitations */
  createInvitation(teamId: string, body?: any): Promise<any> {
    return this.post<any>(`/api/team/${teamId}/invitations`, body);
  }
  /** GET /api/team/{teamId}/members */
  listMembers(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/members`);
  }
  /** PATCH /api/team/{teamId}/members/{memberId} */
  updateMember(teamId: string, memberId: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/team/${teamId}/members/${memberId}`, body);
  }
  /** DELETE /api/team/{teamId}/members/{memberId} */
  deleteMember(teamId: string, memberId: string): Promise<any> {
    return this.delete<any>(`/api/team/${teamId}/members/${memberId}`);
  }
  /** POST /api/webhooks/stripe */
  createStripe(body?: any): Promise<any> {
    return this.post<any>(`/api/webhooks/stripe`, body);
  }
}

export const createMetricsClient = (opts?: ApiClientOptions) => new MetricsClient(opts);
