// AUTO-GENERATED by scripts/gen-sdk.ts — do not edit by hand.
import { ApiClient, type ApiClientOptions } from "../base";

/**
 * Typed client for standard-polls. Construct with a baseUrl pointing at the
 * app origin (e.g. https://standard-lens.vercel.app). All methods return the
 * parsed JSON response and throw ApiError on non-2xx responses.
 */
export class PollsClient extends ApiClient {
  constructor(opts: ApiClientOptions = {}) {
    super(opts);
  }
  /** GET /api/cron/digest */
  listDigest(): Promise<any> {
    return this.get<any>(`/api/cron/digest`);
  }
  /** POST /api/cron/digest */
  createDigest(body?: any): Promise<any> {
    return this.post<any>(`/api/cron/digest`, body);
  }
  /** POST /api/cron/standup */
  createStandup(body?: any): Promise<any> {
    return this.post<any>(`/api/cron/standup`, body);
  }
  /** POST /api/cron/standup-digest */
  createStandupDigest(body?: any): Promise<any> {
    return this.post<any>(`/api/cron/standup-digest`, body);
  }
  /** GET /api/dev/mock-install */
  listMockInstall(): Promise<any> {
    return this.get<any>(`/api/dev/mock-install`);
  }
  /** POST /api/dev/poll */
  createPoll(body?: any): Promise<any> {
    return this.post<any>(`/api/dev/poll`, body);
  }
  /** GET /api/digest/config */
  listConfig(): Promise<any> {
    return this.get<any>(`/api/digest/config`);
  }
  /** PATCH /api/digest/config */
  updateConfig(body?: any): Promise<any> {
    return this.patch<any>(`/api/digest/config`, body);
  }
  /** GET /api/docs */
  listDocs(): Promise<any> {
    return this.get<any>(`/api/docs`);
  }
  /** GET /api/health */
  listHealth(): Promise<any> {
    return this.get<any>(`/api/health`);
  }
  /** GET /api/notifications */
  listNotifications(): Promise<any> {
    return this.get<any>(`/api/notifications`);
  }
  /** POST /api/notifications */
  createNotification(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications`, body);
  }
  /** PATCH /api/notifications/{id}/read */
  updateRead(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/notifications/${id}/read`, body);
  }
  /** POST /api/notifications/read-all */
  createReadAll(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications/read-all`, body);
  }
  /** GET /api/openapi.json */
  listOpenapiJson(): Promise<any> {
    return this.get<any>(`/api/openapi.json`);
  }
  /** GET /api/settings */
  listSettings(): Promise<any> {
    return this.get<any>(`/api/settings`);
  }
  /** PATCH /api/settings */
  updateSetting(body?: any): Promise<any> {
    return this.patch<any>(`/api/settings`, body);
  }
  /** POST /api/slack/events */
  createEvent(body?: any): Promise<any> {
    return this.post<any>(`/api/slack/events`, body);
  }
  /** GET /api/slack/oauth/callback */
  listCallback(): Promise<any> {
    return this.get<any>(`/api/slack/oauth/callback`);
  }
  /** GET /api/slack/oauth/install */
  listInstall(): Promise<any> {
    return this.get<any>(`/api/slack/oauth/install`);
  }
  /** GET /api/standup/prompts */
  listPrompts(): Promise<any> {
    return this.get<any>(`/api/standup/prompts`);
  }
  /** POST /api/standup/prompts */
  createPrompt(body?: any): Promise<any> {
    return this.post<any>(`/api/standup/prompts`, body);
  }
  /** PATCH /api/standup/prompts/{id} */
  updatePrompt(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/standup/prompts/${id}`, body);
  }
  /** GET /api/team */
  listTeam(): Promise<any> {
    return this.get<any>(`/api/team`);
  }
  /** POST /api/team */
  createTeam(body?: any): Promise<any> {
    return this.post<any>(`/api/team`, body);
  }
  /** GET /api/team/{teamId}/invitations */
  listInvitations(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/invitations`);
  }
  /** POST /api/team/{teamId}/invitations */
  createInvitation(teamId: string, body?: any): Promise<any> {
    return this.post<any>(`/api/team/${teamId}/invitations`, body);
  }
  /** GET /api/team/{teamId}/members */
  listMembers(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/members`);
  }
  /** PATCH /api/team/{teamId}/members/{memberId} */
  updateMember(teamId: string, memberId: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/team/${teamId}/members/${memberId}`, body);
  }
  /** DELETE /api/team/{teamId}/members/{memberId} */
  deleteMember(teamId: string, memberId: string): Promise<any> {
    return this.delete<any>(`/api/team/${teamId}/members/${memberId}`);
  }
  /** POST /api/webhooks/stripe */
  createStripe(body?: any): Promise<any> {
    return this.post<any>(`/api/webhooks/stripe`, body);
  }
}

export const createPollsClient = (opts?: ApiClientOptions) => new PollsClient(opts);
