// AUTO-GENERATED by scripts/gen-sdk.ts — do not edit by hand.
import { ApiClient, type ApiClientOptions } from "../base";

/**
 * Typed client for standard-postmortem. Construct with a baseUrl pointing at the
 * app origin (e.g. https://standard-lens.vercel.app). All methods return the
 * parsed JSON response and throw ApiError on non-2xx responses.
 */
export class PostmortemClient extends ApiClient {
  constructor(opts: ApiClientOptions = {}) {
    super(opts);
  }
  /** PATCH /api/actions/{actionId} */
  updateAction(actionId: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/actions/${actionId}`, body);
  }
  /** DELETE /api/actions/{actionId} */
  deleteAction(actionId: string): Promise<any> {
    return this.delete<any>(`/api/actions/${actionId}`);
  }
  /** GET /api/docs */
  listDocs(): Promise<any> {
    return this.get<any>(`/api/docs`);
  }
  /** GET /api/health */
  listHealth(): Promise<any> {
    return this.get<any>(`/api/health`);
  }
  /** GET /api/incidents */
  listIncidents(): Promise<any> {
    return this.get<any>(`/api/incidents`);
  }
  /** POST /api/incidents */
  createIncident(body?: any): Promise<any> {
    return this.post<any>(`/api/incidents`, body);
  }
  /** GET /api/incidents/{id} */
  getIncident(id: string): Promise<any> {
    return this.get<any>(`/api/incidents/${id}`);
  }
  /** PATCH /api/incidents/{id} */
  updateIncident(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/incidents/${id}`, body);
  }
  /** DELETE /api/incidents/{id} */
  deleteIncident(id: string): Promise<any> {
    return this.delete<any>(`/api/incidents/${id}`);
  }
  /** POST /api/incidents/{id}/actions */
  createAction(id: string, body?: any): Promise<any> {
    return this.post<any>(`/api/incidents/${id}/actions`, body);
  }
  /** POST /api/incidents/{id}/embed */
  createEmbed(id: string, body?: any): Promise<any> {
    return this.post<any>(`/api/incidents/${id}/embed`, body);
  }
  /** POST /api/incidents/{id}/links */
  createLink(id: string, body?: any): Promise<any> {
    return this.post<any>(`/api/incidents/${id}/links`, body);
  }
  /** POST /api/intake */
  createIntake(body?: any): Promise<any> {
    return this.post<any>(`/api/intake`, body);
  }
  /** DELETE /api/links/{linkId} */
  deleteLink(linkId: string): Promise<any> {
    return this.delete<any>(`/api/links/${linkId}`);
  }
  /** GET /api/notifications */
  listNotifications(): Promise<any> {
    return this.get<any>(`/api/notifications`);
  }
  /** POST /api/notifications */
  createNotification(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications`, body);
  }
  /** PATCH /api/notifications/{id}/read */
  updateRead(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/notifications/${id}/read`, body);
  }
  /** POST /api/notifications/read-all */
  createReadAll(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications/read-all`, body);
  }
  /** GET /api/openapi.json */
  listOpenapiJson(): Promise<any> {
    return this.get<any>(`/api/openapi.json`);
  }
  /** GET /api/recurrence */
  listRecurrence(): Promise<any> {
    return this.get<any>(`/api/recurrence`);
  }
  /** GET /api/team */
  listTeam(): Promise<any> {
    return this.get<any>(`/api/team`);
  }
  /** POST /api/team */
  createTeam(body?: any): Promise<any> {
    return this.post<any>(`/api/team`, body);
  }
  /** GET /api/team/{teamId}/invitations */
  listInvitations(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/invitations`);
  }
  /** POST /api/team/{teamId}/invitations */
  createInvitation(teamId: string, body?: any): Promise<any> {
    return this.post<any>(`/api/team/${teamId}/invitations`, body);
  }
  /** GET /api/team/{teamId}/members */
  listMembers(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/members`);
  }
  /** PATCH /api/team/{teamId}/members/{memberId} */
  updateMember(teamId: string, memberId: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/team/${teamId}/members/${memberId}`, body);
  }
  /** DELETE /api/team/{teamId}/members/{memberId} */
  deleteMember(teamId: string, memberId: string): Promise<any> {
    return this.delete<any>(`/api/team/${teamId}/members/${memberId}`);
  }
  /** POST /api/webhooks/stripe */
  createStripe(body?: any): Promise<any> {
    return this.post<any>(`/api/webhooks/stripe`, body);
  }
}

export const createPostmortemClient = (opts?: ApiClientOptions) => new PostmortemClient(opts);
