// AUTO-GENERATED by scripts/gen-sdk.ts — do not edit by hand.
import { ApiClient, type ApiClientOptions } from "../base";

/**
 * Typed client for standard-proof. Construct with a baseUrl pointing at the
 * app origin (e.g. https://standard-lens.vercel.app). All methods return the
 * parsed JSON response and throw ApiError on non-2xx responses.
 */
export class ProofClient extends ApiClient {
  constructor(opts: ApiClientOptions = {}) {
    super(opts);
  }
  /** POST /api/collections */
  createCollection(body?: any): Promise<any> {
    return this.post<any>(`/api/collections`, body);
  }
  /** PATCH /api/collections */
  updateCollection(body?: any): Promise<any> {
    return this.patch<any>(`/api/collections`, body);
  }
  /** GET /api/docs */
  listDocs(): Promise<any> {
    return this.get<any>(`/api/docs`);
  }
  /** GET /api/embed/{slug} */
  getEmbed(slug: string): Promise<any> {
    return this.get<any>(`/api/embed/${slug}`);
  }
  /** GET /api/health */
  listHealth(): Promise<any> {
    return this.get<any>(`/api/health`);
  }
  /** GET /api/notifications */
  listNotifications(): Promise<any> {
    return this.get<any>(`/api/notifications`);
  }
  /** POST /api/notifications */
  createNotification(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications`, body);
  }
  /** PATCH /api/notifications/{id}/read */
  updateRead(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/notifications/${id}/read`, body);
  }
  /** POST /api/notifications/read-all */
  createReadAll(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications/read-all`, body);
  }
  /** GET /api/openapi.json */
  listOpenapiJson(): Promise<any> {
    return this.get<any>(`/api/openapi.json`);
  }
  /** GET /api/team */
  listTeam(): Promise<any> {
    return this.get<any>(`/api/team`);
  }
  /** POST /api/team */
  createTeam(body?: any): Promise<any> {
    return this.post<any>(`/api/team`, body);
  }
  /** GET /api/team/{teamId}/invitations */
  listInvitations(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/invitations`);
  }
  /** POST /api/team/{teamId}/invitations */
  createInvitation(teamId: string, body?: any): Promise<any> {
    return this.post<any>(`/api/team/${teamId}/invitations`, body);
  }
  /** GET /api/team/{teamId}/members */
  listMembers(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/members`);
  }
  /** PATCH /api/team/{teamId}/members/{memberId} */
  updateMember(teamId: string, memberId: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/team/${teamId}/members/${memberId}`, body);
  }
  /** DELETE /api/team/{teamId}/members/{memberId} */
  deleteMember(teamId: string, memberId: string): Promise<any> {
    return this.delete<any>(`/api/team/${teamId}/members/${memberId}`);
  }
  /** POST /api/testimonials */
  createTestimonial(body?: any): Promise<any> {
    return this.post<any>(`/api/testimonials`, body);
  }
  /** PATCH /api/testimonials/{id} */
  updateTestimonial(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/testimonials/${id}`, body);
  }
  /** POST /api/webhooks/stripe */
  createStripe(body?: any): Promise<any> {
    return this.post<any>(`/api/webhooks/stripe`, body);
  }
}

export const createProofClient = (opts?: ApiClientOptions) => new ProofClient(opts);
