// AUTO-GENERATED by scripts/gen-sdk.ts — do not edit by hand.
import { ApiClient, type ApiClientOptions } from "../base";

/**
 * Typed client for standard-snippets. Construct with a baseUrl pointing at the
 * app origin (e.g. https://standard-lens.vercel.app). All methods return the
 * parsed JSON response and throw ApiError on non-2xx responses.
 */
export class SnippetsClient extends ApiClient {
  constructor(opts: ApiClientOptions = {}) {
    super(opts);
  }
  /** GET /api/docs */
  listDocs(): Promise<any> {
    return this.get<any>(`/api/docs`);
  }
  /** GET /api/export/json */
  listJson(): Promise<any> {
    return this.get<any>(`/api/export/json`);
  }
  /** GET /api/health */
  listHealth(): Promise<any> {
    return this.get<any>(`/api/health`);
  }
  /** GET /api/notifications */
  listNotifications(): Promise<any> {
    return this.get<any>(`/api/notifications`);
  }
  /** POST /api/notifications */
  createNotification(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications`, body);
  }
  /** PATCH /api/notifications/{id}/read */
  updateRead(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/notifications/${id}/read`, body);
  }
  /** POST /api/notifications/read-all */
  createReadAll(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications/read-all`, body);
  }
  /** GET /api/openapi.json */
  listOpenapiJson(): Promise<any> {
    return this.get<any>(`/api/openapi.json`);
  }
  /** GET /api/shared/{slug} */
  getShared(slug: string): Promise<any> {
    return this.get<any>(`/api/shared/${slug}`);
  }
  /** GET /api/snippets */
  listSnippets(): Promise<any> {
    return this.get<any>(`/api/snippets`);
  }
  /** POST /api/snippets */
  createSnippet(body?: any): Promise<any> {
    return this.post<any>(`/api/snippets`, body);
  }
  /** GET /api/snippets/{id} */
  getSnippet(id: string): Promise<any> {
    return this.get<any>(`/api/snippets/${id}`);
  }
  /** PATCH /api/snippets/{id} */
  updateSnippet(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/snippets/${id}`, body);
  }
  /** DELETE /api/snippets/{id} */
  deleteSnippet(id: string): Promise<any> {
    return this.delete<any>(`/api/snippets/${id}`);
  }
  /** GET /api/snippets/{id}/resolve */
  listResolve(id: string): Promise<any> {
    return this.get<any>(`/api/snippets/${id}/resolve`);
  }
  /** POST /api/snippets/{id}/share */
  createShare(id: string, body?: any): Promise<any> {
    return this.post<any>(`/api/snippets/${id}/share`, body);
  }
  /** GET /api/team */
  listTeam(): Promise<any> {
    return this.get<any>(`/api/team`);
  }
  /** POST /api/team */
  createTeam(body?: any): Promise<any> {
    return this.post<any>(`/api/team`, body);
  }
  /** GET /api/team/{teamId}/invitations */
  listInvitations(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/invitations`);
  }
  /** POST /api/team/{teamId}/invitations */
  createInvitation(teamId: string, body?: any): Promise<any> {
    return this.post<any>(`/api/team/${teamId}/invitations`, body);
  }
  /** GET /api/team/{teamId}/members */
  listMembers(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/members`);
  }
  /** PATCH /api/team/{teamId}/members/{memberId} */
  updateMember(teamId: string, memberId: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/team/${teamId}/members/${memberId}`, body);
  }
  /** DELETE /api/team/{teamId}/members/{memberId} */
  deleteMember(teamId: string, memberId: string): Promise<any> {
    return this.delete<any>(`/api/team/${teamId}/members/${memberId}`);
  }
  /** POST /api/webhooks/stripe */
  createStripe(body?: any): Promise<any> {
    return this.post<any>(`/api/webhooks/stripe`, body);
  }
}

export const createSnippetsClient = (opts?: ApiClientOptions) => new SnippetsClient(opts);
