// AUTO-GENERATED by scripts/gen-sdk.ts — do not edit by hand.
import { ApiClient, type ApiClientOptions } from "../base";

/**
 * Typed client for standard-status. Construct with a baseUrl pointing at the
 * app origin (e.g. https://standard-lens.vercel.app). All methods return the
 * parsed JSON response and throw ApiError on non-2xx responses.
 */
export class StatusClient extends ApiClient {
  constructor(opts: ApiClientOptions = {}) {
    super(opts);
  }
  /** GET /api/docs */
  listDocs(): Promise<any> {
    return this.get<any>(`/api/docs`);
  }
  /** GET /api/health */
  listHealth(): Promise<any> {
    return this.get<any>(`/api/health`);
  }
  /** GET /api/incidents */
  listIncidents(): Promise<any> {
    return this.get<any>(`/api/incidents`);
  }
  /** POST /api/incidents */
  createIncident(body?: any): Promise<any> {
    return this.post<any>(`/api/incidents`, body);
  }
  /** PATCH /api/incidents/{id} */
  updateIncident(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/incidents/${id}`, body);
  }
  /** DELETE /api/incidents/{id} */
  deleteIncident(id: string): Promise<any> {
    return this.delete<any>(`/api/incidents/${id}`);
  }
  /** POST /api/intake */
  createIntake(body?: any): Promise<any> {
    return this.post<any>(`/api/intake`, body);
  }
  /** GET /api/notifications */
  listNotifications(): Promise<any> {
    return this.get<any>(`/api/notifications`);
  }
  /** POST /api/notifications */
  createNotification(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications`, body);
  }
  /** PATCH /api/notifications/{id}/read */
  updateRead(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/notifications/${id}/read`, body);
  }
  /** POST /api/notifications/read-all */
  createReadAll(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications/read-all`, body);
  }
  /** GET /api/openapi.json */
  listOpenapiJson(): Promise<any> {
    return this.get<any>(`/api/openapi.json`);
  }
  /** GET /api/pipelines */
  listPipelines(): Promise<any> {
    return this.get<any>(`/api/pipelines`);
  }
  /** POST /api/pipelines */
  createPipelin(body?: any): Promise<any> {
    return this.post<any>(`/api/pipelines`, body);
  }
  /** GET /api/pipelines/{id} */
  getPipelin(id: string): Promise<any> {
    return this.get<any>(`/api/pipelines/${id}`);
  }
  /** PATCH /api/pipelines/{id} */
  updatePipelin(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/pipelines/${id}`, body);
  }
  /** DELETE /api/pipelines/{id} */
  deletePipelin(id: string): Promise<any> {
    return this.delete<any>(`/api/pipelines/${id}`);
  }
  /** POST /api/pipelines/{id}/deployments */
  createDeployment(id: string, body?: any): Promise<any> {
    return this.post<any>(`/api/pipelines/${id}/deployments`, body);
  }
  /** POST /api/sync */
  createSync(body?: any): Promise<any> {
    return this.post<any>(`/api/sync`, body);
  }
  /** GET /api/team */
  listTeam(): Promise<any> {
    return this.get<any>(`/api/team`);
  }
  /** POST /api/team */
  createTeam(body?: any): Promise<any> {
    return this.post<any>(`/api/team`, body);
  }
  /** GET /api/team/{teamId}/invitations */
  listInvitations(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/invitations`);
  }
  /** POST /api/team/{teamId}/invitations */
  createInvitation(teamId: string, body?: any): Promise<any> {
    return this.post<any>(`/api/team/${teamId}/invitations`, body);
  }
  /** GET /api/team/{teamId}/members */
  listMembers(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/members`);
  }
  /** PATCH /api/team/{teamId}/members/{memberId} */
  updateMember(teamId: string, memberId: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/team/${teamId}/members/${memberId}`, body);
  }
  /** DELETE /api/team/{teamId}/members/{memberId} */
  deleteMember(teamId: string, memberId: string): Promise<any> {
    return this.delete<any>(`/api/team/${teamId}/members/${memberId}`);
  }
  /** POST /api/webhooks/stripe */
  createStripe(body?: any): Promise<any> {
    return this.post<any>(`/api/webhooks/stripe`, body);
  }
}

export const createStatusClient = (opts?: ApiClientOptions) => new StatusClient(opts);
