// AUTO-GENERATED by scripts/gen-sdk.ts — do not edit by hand.
import { ApiClient, type ApiClientOptions } from "../base";

/**
 * Typed client for standard-vault. Construct with a baseUrl pointing at the
 * app origin (e.g. https://standard-lens.vercel.app). All methods return the
 * parsed JSON response and throw ApiError on non-2xx responses.
 */
export class VaultClient extends ApiClient {
  constructor(opts: ApiClientOptions = {}) {
    super(opts);
  }
  /** GET /api/docs */
  listDocs(): Promise<any> {
    return this.get<any>(`/api/docs`);
  }
  /** GET /api/health */
  listHealth(): Promise<any> {
    return this.get<any>(`/api/health`);
  }
  /** GET /api/notifications */
  listNotifications(): Promise<any> {
    return this.get<any>(`/api/notifications`);
  }
  /** POST /api/notifications */
  createNotification(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications`, body);
  }
  /** PATCH /api/notifications/{id}/read */
  updateRead(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/notifications/${id}/read`, body);
  }
  /** POST /api/notifications/read-all */
  createReadAll(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications/read-all`, body);
  }
  /** GET /api/openapi.json */
  listOpenapiJson(): Promise<any> {
    return this.get<any>(`/api/openapi.json`);
  }
  /** GET /api/projects */
  listProjects(): Promise<any> {
    return this.get<any>(`/api/projects`);
  }
  /** POST /api/projects */
  createProject(body?: any): Promise<any> {
    return this.post<any>(`/api/projects`, body);
  }
  /** GET /api/projects/{id} */
  getProject(id: string): Promise<any> {
    return this.get<any>(`/api/projects/${id}`);
  }
  /** PATCH /api/projects/{id} */
  updateProject(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/projects/${id}`, body);
  }
  /** DELETE /api/projects/{id} */
  deleteProject(id: string): Promise<any> {
    return this.delete<any>(`/api/projects/${id}`);
  }
  /** GET /api/projects/{id}/audit */
  listAudit(id: string): Promise<any> {
    return this.get<any>(`/api/projects/${id}/audit`);
  }
  /** POST /api/projects/{id}/decrypt */
  createDecrypt(id: string, body?: any): Promise<any> {
    return this.post<any>(`/api/projects/${id}/decrypt`, body);
  }
  /** GET /api/projects/{id}/dotenv */
  listDotenv(id: string): Promise<any> {
    return this.get<any>(`/api/projects/${id}/dotenv`);
  }
  /** POST /api/projects/{id}/import */
  createImport(id: string, body?: any): Promise<any> {
    return this.post<any>(`/api/projects/${id}/import`, body);
  }
  /** GET /api/projects/{id}/inject */
  listInject(id: string): Promise<any> {
    return this.get<any>(`/api/projects/${id}/inject`);
  }
  /** GET /api/projects/{id}/references */
  listReferences(id: string): Promise<any> {
    return this.get<any>(`/api/projects/${id}/references`);
  }
  /** GET /api/projects/{id}/secrets */
  listSecrets(id: string): Promise<any> {
    return this.get<any>(`/api/projects/${id}/secrets`);
  }
  /** POST /api/projects/{id}/secrets */
  createSecret(id: string, body?: any): Promise<any> {
    return this.post<any>(`/api/projects/${id}/secrets`, body);
  }
  /** GET /api/projects/{id}/tokens */
  listTokens(id: string): Promise<any> {
    return this.get<any>(`/api/projects/${id}/tokens`);
  }
  /** POST /api/projects/{id}/tokens */
  createToken(id: string, body?: any): Promise<any> {
    return this.post<any>(`/api/projects/${id}/tokens`, body);
  }
  /** PATCH /api/secrets/{id} */
  updateSecret(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/secrets/${id}`, body);
  }
  /** DELETE /api/secrets/{id} */
  deleteSecret(id: string): Promise<any> {
    return this.delete<any>(`/api/secrets/${id}`);
  }
  /** GET /api/team */
  listTeam(): Promise<any> {
    return this.get<any>(`/api/team`);
  }
  /** POST /api/team */
  createTeam(body?: any): Promise<any> {
    return this.post<any>(`/api/team`, body);
  }
  /** GET /api/team/{teamId}/invitations */
  listInvitations(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/invitations`);
  }
  /** POST /api/team/{teamId}/invitations */
  createInvitation(teamId: string, body?: any): Promise<any> {
    return this.post<any>(`/api/team/${teamId}/invitations`, body);
  }
  /** GET /api/team/{teamId}/members */
  listMembers(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/members`);
  }
  /** PATCH /api/team/{teamId}/members/{memberId} */
  updateMember(teamId: string, memberId: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/team/${teamId}/members/${memberId}`, body);
  }
  /** DELETE /api/team/{teamId}/members/{memberId} */
  deleteMember(teamId: string, memberId: string): Promise<any> {
    return this.delete<any>(`/api/team/${teamId}/members/${memberId}`);
  }
  /** DELETE /api/tokens/{id} */
  deleteToken(id: string): Promise<any> {
    return this.delete<any>(`/api/tokens/${id}`);
  }
  /** POST /api/webhooks/stripe */
  createStripe(body?: any): Promise<any> {
    return this.post<any>(`/api/webhooks/stripe`, body);
  }
}

export const createVaultClient = (opts?: ApiClientOptions) => new VaultClient(opts);
