// AUTO-GENERATED by scripts/gen-sdk.ts — do not edit by hand.
import { ApiClient, type ApiClientOptions } from "../base";

/**
 * Typed client for standard-workspace. Construct with a baseUrl pointing at the
 * app origin (e.g. https://standard-lens.vercel.app). All methods return the
 * parsed JSON response and throw ApiError on non-2xx responses.
 */
export class WorkspaceClient extends ApiClient {
  constructor(opts: ApiClientOptions = {}) {
    super(opts);
  }
  /** GET /api/depsync */
  listDepsync(): Promise<any> {
    return this.get<any>(`/api/depsync`);
  }
  /** GET /api/docs */
  listDocs(): Promise<any> {
    return this.get<any>(`/api/docs`);
  }
  /** GET /api/health */
  listHealth(): Promise<any> {
    return this.get<any>(`/api/health`);
  }
  /** POST /api/health/run */
  createRun(body?: any): Promise<any> {
    return this.post<any>(`/api/health/run`, body);
  }
  /** GET /api/notifications */
  listNotifications(): Promise<any> {
    return this.get<any>(`/api/notifications`);
  }
  /** POST /api/notifications */
  createNotification(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications`, body);
  }
  /** PATCH /api/notifications/{id}/read */
  updateRead(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/notifications/${id}/read`, body);
  }
  /** POST /api/notifications/read-all */
  createReadAll(body?: any): Promise<any> {
    return this.post<any>(`/api/notifications/read-all`, body);
  }
  /** GET /api/openapi.json */
  listOpenapiJson(): Promise<any> {
    return this.get<any>(`/api/openapi.json`);
  }
  /** GET /api/sessions */
  listSessions(): Promise<any> {
    return this.get<any>(`/api/sessions`);
  }
  /** POST /api/sessions */
  createSession(body?: any): Promise<any> {
    return this.post<any>(`/api/sessions`, body);
  }
  /** GET /api/sessions/{id}/logs */
  listLogs(id: string): Promise<any> {
    return this.get<any>(`/api/sessions/${id}/logs`);
  }
  /** POST /api/sessions/{id}/stop */
  createStop(id: string, body?: any): Promise<any> {
    return this.post<any>(`/api/sessions/${id}/stop`, body);
  }
  /** GET /api/team */
  listTeam(): Promise<any> {
    return this.get<any>(`/api/team`);
  }
  /** POST /api/team */
  createTeam(body?: any): Promise<any> {
    return this.post<any>(`/api/team`, body);
  }
  /** GET /api/team/{teamId}/invitations */
  listInvitations(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/invitations`);
  }
  /** POST /api/team/{teamId}/invitations */
  createInvitation(teamId: string, body?: any): Promise<any> {
    return this.post<any>(`/api/team/${teamId}/invitations`, body);
  }
  /** GET /api/team/{teamId}/members */
  listMembers(teamId: string): Promise<any> {
    return this.get<any>(`/api/team/${teamId}/members`);
  }
  /** PATCH /api/team/{teamId}/members/{memberId} */
  updateMember(teamId: string, memberId: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/team/${teamId}/members/${memberId}`, body);
  }
  /** DELETE /api/team/{teamId}/members/{memberId} */
  deleteMember(teamId: string, memberId: string): Promise<any> {
    return this.delete<any>(`/api/team/${teamId}/members/${memberId}`);
  }
  /** GET /api/tunnels */
  listTunnels(): Promise<any> {
    return this.get<any>(`/api/tunnels`);
  }
  /** POST /api/tunnels */
  createTunnel(body?: any): Promise<any> {
    return this.post<any>(`/api/tunnels`, body);
  }
  /** PATCH /api/tunnels/{id} */
  updateTunnel(id: string, body?: any): Promise<any> {
    return this.patch<any>(`/api/tunnels/${id}`, body);
  }
  /** DELETE /api/tunnels/{id} */
  deleteTunnel(id: string): Promise<any> {
    return this.delete<any>(`/api/tunnels/${id}`);
  }
  /** POST /api/webhooks/stripe */
  createStripe(body?: any): Promise<any> {
    return this.post<any>(`/api/webhooks/stripe`, body);
  }
}

export const createWorkspaceClient = (opts?: ApiClientOptions) => new WorkspaceClient(opts);
